# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [19]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[86, 18, 26, ..., 41, 87, 71],
       [93, 32, 24, ..., 15, 79, 99],
       [ 7, 66,  1, ..., 59, 63, 33],
       ...,
       [27, 12, 91, ..., 45, 41, 68],
       [69, 44, 13, ..., 12,  8, 76],
       [18, 83,  0, ..., 33, 13, 76]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [20]:
# 1. 确定列的数量
# .shape 属性来获取数组 A 的形状，它返回一个元组，其中第一个元素是行数，第二个元素是列数。
# Свойство .shape позволяет получить форму массива A. Оно возвращает кортеж, первый элемент которого - количество строк, а второй - количество столбцов.
num = A.shape[1]

# 2. 生成随机列顺序
# 2. Генерировать случайный порядок столбцов
random_order = np.random.permutation(num)

# 3. 应用随机顺序
# 3. Применение случайного порядка
A_randomized = A[:, random_order]

A_randomized

array([[44, 22, 19, ..., 68, 87, 41],
       [96, 10, 81, ..., 31, 79, 15],
       [52,  0,  0, ..., 74, 63, 59],
       ...,
       [73, 85,  3, ..., 80, 41, 45],
       [67, 26, 37, ..., 67,  8, 12],
       [80, 61, 23, ..., 44, 13, 33]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [21]:
# 计算奇数列和偶数列的和
# Вычислить сумму четных и нечетных серий
sum_even_columns = A[:, 0::2].sum(axis=1)  # 偶数列（从0开始，步长为2）的和 Сумма четного ряда (начиная с 0 и с шагом 2)
sum_odd_columns = A[:, 1::2].sum(axis=1)   # 奇数列（从1开始，步长为2）的和 Сумма нечетного ряда (начиная с 1 и с шагом 2)

# 计算奇数列和的平均值
# Вычислить среднее значение сумм нечетных столбцов
average_sum_odd_columns = sum_odd_columns.mean()

# 选择满足条件的行：偶数列的和大于奇数列的和的平均值
# Выбираем строки, в которых выполняется условие: сумма четных столбцов больше среднего значения сумм нечетных столбцов.
selected_rows = A[sum_even_columns > average_sum_odd_columns]
selected_rows

array([[86, 18, 26, ..., 41, 87, 71],
       [93, 32, 24, ..., 15, 79, 99],
       [ 7, 66,  1, ..., 59, 63, 33],
       ...,
       [80, 86, 47, ..., 20, 32, 77],
       [23, 35, 90, ..., 60,  2, 60],
       [27, 12, 91, ..., 45, 41, 68]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [22]:
# 计算每一行的最大值和最小值
# Вычислить максимальное и минимальное значения для каждой строки
max_per_row = A.max(axis=1)
min_per_row = A.min(axis=1)

# 计算每一行的最大值和最小值之差
# Вычислить разность между максимальным и минимальным значениями для каждой строки
difference = max_per_row - min_per_row

# 找到最大差值的行索引
# Найти индекс ряда с наибольшей разницей
max_diff_index = np.argmax(difference)
max_diff_index 

1

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [23]:
# 将 A 展平为一维数组
# Сплющивание A в одномерный массив
flattened_A = A.flatten()

# 使用 argsort() 获取排序后的索引
# Использование функции argsort() для получения отсортированных индексов
sorted_indices = np.argsort(flattened_A)

# 创建一个新数组，其元素是排序位置（从 1 开始计数）
# Создать новый массив, элементами которого являются отсортированные позиции (считая от 1)
sorted_positions = np.argsort(sorted_indices) + 1

# 将新数组重塑为原始数组 A 的形状 A.shape用于获取原数组的形状
# Переформирование нового массива в форму исходного массива A A.shape используется для получения формы исходного массива
result = sorted_positions.reshape(A.shape)
result


array([[8727, 1901, 2777, ..., 4183, 8856, 7275],
       [9442, 3280, 2503, ..., 1643, 8071, 9916],
       [ 853, 6719,  196, ..., 6069, 6447, 3426],
       ...,
       [2807, 1265, 9166, ..., 4648, 4259, 6923],
       [7048, 4505, 1451, ..., 1366,  934, 7729],
       [1951, 8440,   54, ..., 3393, 1412, 7733]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [24]:
# 找到每一行的最小值和最大值
# Найти минимальное и максимальное значения для каждой строки
min_values = A.min(axis=1, keepdims=True)
max_values = A.max(axis=1, keepdims=True)

# 应用最小-最大归一化
# Применить нормализацию по принципу min-max
normalized_A = (A - min_values) / (max_values - min_values)
normalized_A

array([[0.86597938, 0.16494845, 0.24742268, ..., 0.40206186, 0.87628866,
        0.71134021],
       [0.93939394, 0.32323232, 0.24242424, ..., 0.15151515, 0.7979798 ,
        1.        ],
       [0.07142857, 0.67346939, 0.01020408, ..., 0.60204082, 0.64285714,
        0.33673469],
       ...,
       [0.25      , 0.09375   , 0.91666667, ..., 0.4375    , 0.39583333,
        0.67708333],
       [0.71276596, 0.44680851, 0.11702128, ..., 0.10638298, 0.06382979,
        0.78723404],
       [0.18181818, 0.83838384, 0.        , ..., 0.33333333, 0.13131313,
        0.76767677]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [25]:
# 创建一个形状为10的一维数组，其元素为1到10
# Создать одномерный массив формы 10 с элементами от 1 до 10
factors = np.arange(1, 11)

# 利用NumPy的广播机制将A乘以factors，得到所需的三维数组
# Умножение A на коэффициенты с использованием механизма трансляции NumPy для получения требуемого 3D-массива
B = A * factors[:, np.newaxis, np.newaxis]
B

array([[[ 86,  18,  26, ...,  41,  87,  71],
        [ 93,  32,  24, ...,  15,  79,  99],
        [  7,  66,   1, ...,  59,  63,  33],
        ...,
        [ 27,  12,  91, ...,  45,  41,  68],
        [ 69,  44,  13, ...,  12,   8,  76],
        [ 18,  83,   0, ...,  33,  13,  76]],

       [[172,  36,  52, ...,  82, 174, 142],
        [186,  64,  48, ...,  30, 158, 198],
        [ 14, 132,   2, ..., 118, 126,  66],
        ...,
        [ 54,  24, 182, ...,  90,  82, 136],
        [138,  88,  26, ...,  24,  16, 152],
        [ 36, 166,   0, ...,  66,  26, 152]],

       [[258,  54,  78, ..., 123, 261, 213],
        [279,  96,  72, ...,  45, 237, 297],
        [ 21, 198,   3, ..., 177, 189,  99],
        ...,
        [ 81,  36, 273, ..., 135, 123, 204],
        [207, 132,  39, ...,  36,  24, 228],
        [ 54, 249,   0, ...,  99,  39, 228]],

       ...,

       [[688, 144, 208, ..., 328, 696, 568],
        [744, 256, 192, ..., 120, 632, 792],
        [ 56, 528,   8, ..., 472, 504, 264

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [26]:
#提取偶数列
# Извлечение четных столбцов
even_columns = A[:, ::2]

# 提取奇数列
# Извлечение нечетных серий
odd_columns = A[:, 1::2]

new_A = np.concatenate((even_columns,odd_columns), axis=1)
new_A


array([[86, 26, 67, ..., 71, 41, 71],
       [93, 24, 45, ..., 60, 15, 99],
       [ 7,  1,  9, ..., 91, 59, 33],
       ...,
       [27, 91, 49, ..., 78, 45, 68],
       [69, 13, 67, ..., 12, 12, 76],
       [18,  0, 32, ..., 15, 33, 76]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [ ]:
# 创建一个布尔数组，其中元素表示 A 中的元素是否大于 5
# Создать булевский массив, элементы которого указывают, больше ли элементов в A, чем 5
A_5 = A > 5

# 使用 np.all() 检查哪些行的所有元素都大于 5
# Используйте np.all() для проверки того, в каких строках все элементы больше 5
all_5 = np.all(A_5, axis=1)

# 统计满足条件的行数
# Количество подсчитанных строк, удовлетворяющих условиям
A_all_5 = np.sum(all_5)
A_all_5

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [ ]:
A_split = np.split(A, 10)

A_mean = np.sum(A_split, axis=0) / 10
A_mean

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [ ]:
A_flatten = A.flatten()

A_array, index  = np.unique(A_flatten, return_index=True)

A_unique = A_flatten[np.sort(index)]
A_unique

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

In [ ]:
A_mean = np.mean(A, axis=0)

B = np.sqrt(np.sum((A - A_mean)**2, axis = 1))
B

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [ ]:
A_where = np.where(A < 50, A*2, A*3)
A_where

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [ ]:
def moving(arr, window):
    A_cumsum = np.cumsum(arr, dtype=float)
    A_cumsum[window:] = A_cumsum[window:] - A_cumsum[:-window]
    return A_cumsum[window - 1:] / window

A_flatten = A.flatten()

A3 = moving(A_flatten, 3)
A5 = moving(A_flatten, 5)
A10 = moving(A_flatten, 10)

max_len = max(len(A3), len(A5), len(A10))

B3 = np.zeros(max_len)
B5 = np.zeros(max_len)
B10 = np.zeros(max_len)

B3[:len(A3)] = A3
B5[:len(A5)] = A5
B10[:len(A10)] = A10

sum_A = B3 + B5 + B10
sum_A

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [27]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 0, 0, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [28]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2142

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [29]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


0.6555878446433502

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.